### ISSUE TITLE
Running Tests

### ISSUE THREAD

**Issue by balasankarc** [nov/attr_required#2]
I did a `bundle install` and then when I tried `bundle exec rake`, I am getting the following error

fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
/usr/bin/ruby2.1 -I/home/balasankarc/.rvm/gems/ruby-2.1.0/gems/rspec-core-3.1.7/lib:/home/balasankarc/.rvm/gems/ruby-2.1.0/gems/rspec-support-3.1.2/lib /home/balasankarc/.rvm/gems/ruby-2.1.0/gems/rspec-core-3.1.7/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git

AttrOptional
  .attr_optional
    should define accessible attributes
    should be inherited
    when already required
      should be optional (FAILED - 1)
    when AttrRequired not included
      should do nothing
  .attr_optional?
    should answer whether the attributes is optional or not (FAILED - 2)
  #attr_optional?
    should answer whether the attributes is optional or not (FAILED - 3)
  .optional_attributes
    should return all optional attributes keys
  #optional_attributes
    should return optional attributes keys
  .undef_optional_attributes
    should undefine accessors and remove from optional attributes

AttrRequired
  .attr_required
    should define accessible attributes
    should be inherited
    when already optional
      should be optional (FAILED - 4)
    when AttrOptional not included
      should do nothing
  .attr_required?
    should answer whether the attributes is required or not (FAILED - 5)
  #attr_required?
    should answer whether the attributes is required or not (FAILED - 6)
  #attr_missing?
    should answer whether any attributes are missing (FAILED - 7)
  #attr_missing!
    should raise AttrMissing error when any attributes are missing
  #attr_missing
    should return missing attributes keys
  .required_attributes
    should return all required attributes keys
  #required_attributes
    should return required attributes keys
  .undef_required_attributes
    should undefine accessors and remove from required attributes

Failures:

  1) AttrOptional.attr_optional when already required should be optional
     Failure/Error: @c.attr_required?(:attr_required_b).should be_false
       expected false to respond to `false?`
     # ./spec/attr_optional_spec.rb:23:in `block (4 levels) in <top (required)>'

  2) AttrOptional.attr_optional? should answer whether the attributes is optional or not
     Failure/Error: A.attr_optional?(:attr_optional_a).should be_true
       expected true to respond to `true?`
     # ./spec/attr_optional_spec.rb:37:in `block (3 levels) in <top (required)>'

  3) AttrOptional#attr_optional? should answer whether the attributes is optional or not
     Failure/Error: @a.attr_optional?(:attr_optional_a).should be_true
       expected true to respond to `true?`
     # ./spec/attr_optional_spec.rb:46:in `block (3 levels) in <top (required)>'

  4) AttrRequired.attr_required when already optional should be optional
     Failure/Error: @c.attr_required?(:attr_optional_b).should be_true
       expected true to respond to `true?`
     # ./spec/attr_required_spec.rb:23:in `block (4 levels) in <top (required)>'

  5) AttrRequired.attr_required? should answer whether the attributes is required or not
     Failure/Error: A.attr_required?(:attr_required_a).should be_true
       expected true to respond to `true?`
     # ./spec/attr_required_spec.rb:37:in `block (3 levels) in <top (required)>'

  6) AttrRequired#attr_required? should answer whether the attributes is required or not
     Failure/Error: @a.attr_required?(:attr_required_a).should be_true
       expected true to respond to `true?`
     # ./spec/attr_required_spec.rb:46:in `block (3 levels) in <top (required)>'

  7) AttrRequired#attr_missing? should answer whether any attributes are missing
     Failure/Error: @a.attr_missing?.should be_true
       expected true to respond to `true?`
     # ./spec/attr_required_spec.rb:56:in `block (3 levels) in <top (required)>'

Deprecation Warnings:

Using `should` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` instead. Called from /home/balasankarc/packaging/attr-required/source/attr_required-1.0.0/spec/attr_optional_spec.rb:10:in `block (3 levels) in <top (required)>'.

If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.

1 deprecation warning total

Finished in 0.01502 seconds (files took 0.14387 seconds to load)
21 examples, 7 failures

Failed examples:

rspec ./spec/attr_optional_spec.rb:22 # AttrOptional.attr_optional when already required should be optional
rspec ./spec/attr_optional_spec.rb:36 # AttrOptional.attr_optional? should answer whether the attributes is optional or not
rspec ./spec/attr_optional_spec.rb:45 # AttrOptional#attr_optional? should answer whether the attributes is optional or not
rspec ./spec/attr_required_spec.rb:22 # AttrRequired.attr_required when already optional should be optional
rspec ./spec/attr_required_spec.rb:36 # AttrRequired.attr_required? should answer whether the attributes is required or not
rspec ./spec/attr_required_spec.rb:45 # AttrRequired#attr_required? should answer whether the attributes is required or not
rspec ./spec/attr_required_spec.rb:55 # AttrRequired#attr_missing? should answer whether any attributes are missing
Coverage report generated for RSpec to /home/balasankarc/packaging/attr-required/source/attr_required-1.0.0/coverage. 64 / 64 LOC (100.0%) covered.
/usr/bin/ruby2.1 -I/home/balasankarc/.rvm/gems/ruby-2.1.0/gems/rspec-core-3.1.7/lib:/home/balasankarc/.rvm/gems/ruby-2.1.0/gems/rspec-support-3.1.2/lib /home/balasankarc/.rvm/gems/ruby-2.1.0/gems/rspec-core-3.1.7/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed

Can you help me out?

**Comment by nov** [comment]
ah, because of rspec change.
will fix when I have time.

**Comment by balasankarc** [comment]
Ok. Thanks.

**Comment by balasankarc** [comment]
Runs fine with Rspec 3.
