### ISSUE TITLE
New release with Rspec update

### ISSUE THREAD

**Issue by balasankarc** [nov/attr_required#3]
Hi,
Can you please release a new version with the RSpec bump? I am packaging this gem for Debian and we are having a transition from RSpec 2 to RSpec 3 in Debian. So, a newer version with RSpec bump would be less work (or, I'll have to upload the one with RSpec 2 and then patch out every change to support RSpec until you update the source).

It would be a great help if you could release a new version. Thanks

**Comment by nov** [comment]
sorry for my late response.
this issue should be closed in cee0ea53ab719a7a73c26a23e279d175f9fcf2a4
